spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arthricare?serverTimezone=UTC
    username: root
    password: root

post-image-save-path: D:\321Project\ArthriCare git\ArthriCare_Back\src\main\resources\static\uploadImages\
puzzle-image-save-path: D:\321Project\ArthriCare git\ArthriCare_Back\src\main\resources\static\puzzleImage\
avatar-image-save-path: D:\321Project\ArthriCare git\ArthriCare_Back\src\main\resources\static\avatar\
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8181






